FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install python3.10 python3.10-dev python3.10-venv pip wget vim ffmpeg

# 设置Python3.10为默认Python版本
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

USER root
WORKDIR /app/content-extract

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
